### ISSUE TITLE
Failed to set power state - Not connected

### ISSUE THREAD

**Issue by mane87** [solowalker27/homebridge-benq-projector#1]
Hi,
first of all: Thank you for your work on this plugin.

I am having troubles getting this plugin to run.
I receive the following error
![Screenshot 2019-06-08 at 12 03 06](https://user-images.githubusercontent.com/1901943/59145532-80077800-89e5-11e9-9537-fd7f6dff2bb9.png)

My USB-RS232 adaptor is connected to *ttyUSB0*
![Screenshot 2019-06-08 at 12 04 28](https://user-images.githubusercontent.com/1901943/59145548-aa593580-89e5-11e9-9ec8-90819b12b0d2.png)

My config looks like this:
```
{
            "accessory": "BenQ-Projector",
            "name": "Projector",
            "model": "W1070",
            "adapter": "/dev/ttyUSB0",
            "inputs": [
                {
                    "input": "hdmi",
                    "label": "Apple TV"
                },
                {
                    "input": "hdmi2",
                    "label": "Raspberry Pi"
                }
            ]
        }
```

Any idea what could cause this issue?
Any help would be highly appreciated.

**Comment by solowalker27** [comment]
Sorry for the delay in responding.

Unfortunately, I don't know what could be causing that. Are you able to connect to the serial port directly to make sure it works? It's been a while since I set mine up but if you need help, I can try to find the pages I used to walk me through it.

**Comment by solowalker27** [comment]
Hope you were able to get this resolved. If not, feel free to reopen or create a new issue.
