### ISSUE TITLE
Plug-in v2.1.0 not available on npm registry

### ISSUE THREAD

**Issue by johannrichard** [solowalker27/homebridge-benq-projector#10]
The plug-in download fails when trying to install v2.1.0 / latest from the npm registry, albeit the fact that npm lists this as the latest version.

**Comment by solowalker27** [comment]
This is probably the same as https://github.com/solowalker27/homebridge-benq-projector/issues/9. Closing this as duplicate. You can reopen with more information if you don't think this is correct.
