### ISSUE TITLE
Projector volume controls do not register

### ISSUE THREAD

**Issue by ledhed2222** [solowalker27/homebridge-benq-projector#4]
First off - killer plugin. Input selection and on/off are working great for me. Thanks!

However, I cannot get Home.app to recognize any volume controls for the projector. I see that you're registering the `Service.TelevisionSpeaker` here, and there doesn't seem to be any condition around calling this function: https://github.com/solowalker27/homebridge-benq-projector/blob/master/index.js#L458

With debug mode on in Homebridge I don't see anything out-of-the-ordinary either.

Is the volume control supposed to appear as a different accessory or something?

**Comment by solowalker27** [comment]
Volume doesn't appear as a different accessory. I'm only supporting the built-in volume control for the remote. On an iPhone, you can use the physical volume buttons on your iPhone while the remote for the projector is visible. I don't think there's a way to control it from an iPad at this point. You can try third party apps but I don't think televisions have been exposed to those yet.
