### ISSUE TITLE
Projector gradually becomes less and less responsive to control if Homebridge is not restarted

### ISSUE THREAD

**Issue by sskrede** [solowalker27/homebridge-benq-projector#6]
Thank you for working on this plugin, it's exactly what I need for my setup!

I have observed this problem over the last few weeks, trying to figure out a solution. After about 1 hour, the reaction time between telling Homebridge to start the projector and the projector actually starting gradually increases, up until the point where it no longer responds at all.
If I restart the Homebridge process, it goes back to a reasonable amount of delay.

My projector is a SB840, and from all documentation and testing should have the same serial commands as other Benq projectors. However, the plugin returns several errors when trying to gather states from the projector, such as Input state, Power state and Mute state.

System details:

Node.js v12.16.1
Npm v6.14.3
Homebridge v0.4.53
Config-ui-x v4.13.0
Homebridge-Benq-Projector v1.0.6
HW: Raspberry Pi 2B1.1/3B1.2
2 different USB-RS232 dongles
BenQ SB840 projector
Wired ethernet connection

Please tell me if you would need any details, configuration files, log files or other information.

**Comment by solowalker27** [comment]
I occasionally see performance degradation on my set up with my W1070 projector. It's the one thing I wish I knew how to solve. Unfortunately, I'm a noob with Serial stuff so I don't know what else to do. I've just resigned myself to needing to restart it periodically. 

If you have a log for the errors you described, I can try to look into those.

**Comment by sskrede** [comment]
[homebridge.log](https://github.com/solowalker27/homebridge-benq-projector/files/4463864/homebridge.log)

Earlier today I tried starting the projector up via the Home-app, and it took 12 seconds or so. Tried it again, and it took just about exactly 2 minutes. The uptime is 18 days 2 hours right now, it makes no sense to me. I'm starting to feel like the fix for now will be to just run a cron job every few hours rebooting the pi, but it seems like one of those "if it's stupid and it works, it's still stupid" kind of situations.. Perhaps I'm putting too much into this. I'd appreciate any pointers you could give me as to what I'm doing wrong on my end, and don't hesitate to ask if there's anything more I can do in order to help figuring this out :) 

My config looks like this:

`{
    "bridge": {
        "name": "Lekerommet",
        "username": "0E:52:36:31:3A:1A",
        "port": 51396,
        "pin": "111-111-111"
    },
    "accessories": [
        {
            "name": "Projektor",
            "model": "SP840",
            "adapter": "/dev/ttyUSB0",
            "inputs": [
                {
                    "input": "hdmi",
                    "label": "Apple TV"
                }
            ],
            "baudrate": 9600,
            "pollingInterval": 1000,
            "accessory": "BenQ-Projector"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "AppleTvPlatform",
            "devices": [
                {
                    "name": "Projektor",
                    "credentials": "XXXXXXXXXX-letters-n-stuff",
                    "isOnOffSwitchEnabled": true,
                    "isPlayPauseSwitchEnabled": false,
                    "pollingInterval": 1000
                },
                {
                    "name": "Stuen",
                    "credentials": "XXXXXXXX-and-so-on",
                    "isOnOffSwitchEnabled": true,
                    "isPlayPauseSwitchEnabled": false,
                    "pollingInterval": 1000
                }
            ],
            "isApiEnabled": false,
            "apiPort": 40304,
            "apiToken": "<YOUR-TOKEN>"
        }
    ]
}`

**Comment by solowalker27** [comment]
Okay, I made time to revisit this and drastically simplified the serial code by switching to a higher level package and not relying on the other functions. I've been testing it for a bit and it seems to work okay for me. If you'd like, you can check it out and let me know how it goes. I've got it checked in here. https://github.com/solowalker27/homebridge-benq-projector/tree/serial-io

**Comment by sskrede** [comment]
Hello Sir, and thank you for taking the time to work on this! I will try the new version out and see if it performs better. Right now I have resorted to restarting the homebridge process every hour. Looking forward to having a look, and once again, thank you. If this works out, I’ll want to buy you a beer dear Sir.

**Comment by solowalker27** [comment]
I shipped this to npm a week ago. I haven't heard of issues from anyone. npm says it's had 53 downloads. How has it been working for you? If performance is better and you've had no other issues, feel free to close this.

**Comment by sskrede** [comment]
I did start installing it, but inexperience with installing without npm slowed me down to a point where I couldn’t get it done before I had to travel for an urgent work project. Glad to hear that it’s on NPM for me when I get back this weekend. Looking forward to testing it out, and I am confident that it will solve my issues.

If you want me to, I can close this issue and reach out in the unlikely case this doesn’t fix it. Sorry for being slow with this.

**Comment by solowalker27** [comment]
No, it’s fine. I can be patient. Just bumping this make sure it didn’t get forgotten. Let me know how it goes when you get a chance to try it.

**Comment by sskrede** [comment]
It’s certainly not forgotten, although admittedly your reminder has served its purpose, and I appreciate that. I would like to make a contribution to you for the time and effort you have put into this project and others like it. Would you consider making this possible in some way?

**Comment by sskrede** [comment]
The update works perfectly, thank you so much!
