### ISSUE TITLE
version 2.0.0 requires unavailable dependency

### ISSUE THREAD

**Issue by ledhed2222** [solowalker27/homebridge-benq-projector#9]
Hey there,

Trying to install v2.0.0 but one of the dependencies is `serial-io@2.0.0` which doesn't exist on npmjs.com. As a result, my `npm` cannot install your update. To be clear, `serial-io@1.2.0` exists, just not that version.

**Comment by drpodmeer** [comment]
any news? still canot install or update you plug in :(

**Comment by solowalker27** [comment]
Pushed an update to fix this as v2.1.1. Please try installing that version and let me know if it doesn't work.

**Comment by drpodmeer** [comment]
its working now! thanks a lot 🤗
